### ISSUE TITLE
Error Django 5.1.4 - BloomerpFileField (set null=True)

### ISSUE THREAD

**Issue by emicba126** [DavidBloomer11/Bloomerp#1]
Hi!
Test project with Django 5.1.4 and found this error when "python manage.py makemigrations sales":

ERRORS:
sales.Product.image: (fields.E320) Field specifies on_delete=SET_NULL, but cannot be null.
        HINT: Set null=True argument on the field, or change the on_delete rule.

I find the file in bloomerp/models/fields.py and add (kwargs['null'] = True), then no Error in makemigratios:

class BloomerpFileField(models.ForeignKey):
    def __init__(self, *args, allowed_extensions=None, **kwargs):
        """
        Initialize BloomerpFileField with a ForeignKey to the File model and optional file type validation.
        `allowed_extensions` specifies allowed file types; if '__all__' or None, all are allowed.
        """
        self.allowed_extensions = allowed_extensions if allowed_extensions is not None else '__all__'
        kwargs['to'] = 'bloomerp.File'
        kwargs['on_delete'] = models.SET_NULL
        **kwargs['null'] = True  # !!! Add Line !!!**
        
        super().__init__(*args, **kwargs)

I don't know if Django 5 requires declaring this variable: "null=True" in models.ForeignKey

**Comment by DavidBloomer11** [comment]
Hi, this should now be fixed in the latest commit. Thanks for commenting. Happy holidays
